# Generated by Django 4.0.1 on 2022-01-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskoccurrence',
            name='subtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_occurrence_subtask', to='Tasks.taskoccurrence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtaskoccurrence',
            name='task_occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tasks.taskoccurrence'),
        ),
    ]
